check if pushed==true

diff --git a/.github/workflows/publish_benchmarks.yml b/.github/workflows/publish_benchmarks.yml
--- a/.github/workflows/publish_benchmarks.yml
+++ b/.github/workflows/publish_benchmarks.yml
@@ -127,18 +127,12 @@ jobs:
           # Whether to push the commit and, if any, its tags to the repo. It can also be used to set the git push arguments (see the paragraph below for more info)
           # Default: true
           push: true
-      
-          # The arguments for the `git rm` command (see the paragraph below for more info)
-          # Default: ''
-          #remove: './dir/old_file.js'
-      
-          # Arguments for the git tag command (the tag name always needs to be the first word not preceded by an hyphen)
-          # Default: ''
-          #tag: 'v1.0.0 --force'
-      
-          # Arguments for the git push --tags command (any additional argument will be added after --tags)
-          # Default: ''
-          #tag_push: '--force'
+      - name: fail if outputs.pushed is not true
+        run: |
+          if [ "${{ steps.commit.outputs.pushed }}" != "true" ]; then
+            echo "Commit failed"
+            exit 1
+          fi
 #      - uses: stefanzweifel/git-auto-commit-action@v5
 #        with:
 #          # Optional. Commit message for the created commit.
